pub const CHOICERS: &[&str] = &[
    // ch1
    "Yes", "No",
    "Not yet", "Yes. Ask.",
    "Not yet", "Yes",
    "Good", "Bad",
    "Yes", "No",
    "Listen", "No",
    "Listen", "We know it already",
    "I'll be Your Subject", "Keep Dreaming",
    "I know", "Really!?",
    "I know", "Really!?",
    "Yes", "Don't",
    "I can handle it", ".....",
    "Yes", "No",
    "Yes", "No",
    "Yes", "No",
    "Yes", "No",
    "Yes", "No",
    "Yes", "No",
    "Yes", "No",
    "Crumpled paper", "LANCER labelled paper", "Neat paper",
    "Yes", "No",
    "Noelle", "Family", "Illness", "Nothing",
    "No No No No No No No No No", "Yes",
    "Sit", "Don't Sit",
    "Stick fingers", "Don't",
    "Yes", "No",
    "Kris", "Hippopotamus",
    "Onion", "Beauty", "Asriel II", "Disgusting",
    "Open Fridge", "Don't", "See photos",
    "Asriel", "Neighbors", "Sister", "Nothing",
    "Neighbor", "Memories", "Go Away", "Nothing",
    "Buy", "No",
    "Buy", "No",
    "Buy", "No",
    "Buy", "No",
    "What's TP?", "Secret", "Gaining TP", "Bye",
    "Pacify", "Healing", "Fact", "Bye",
    "Warning", "Attack", "Fact", "Bye",
    "Reviving", "Acting", "Fact", "Bye",
    "Throw $1", "Do not",
    "Make Ralsei try it", "Try it", "Decline",
    "Flowers", "Saucer", "Chalk", "Nothing",
    "Add Spade", "Add Diamond", "Swap",
    "Perpetuate", "Do not",
    "Take", "Do not",
    "Yes", "She'll be fine",
    "Go Left", "Go Right",
    "Fix Item", "Leave", "Fix Us",
    "Buy", "Do not",
    "Buy", "Do not",
    "Buy", "Do not",
    "Alphys", "Dark World", "Help you", "Nothing",
    "Asriel", "Job", "Co-Workers", "No",
    "Fruit Juice", "Nothing",
    "Yes", "No",
    "Yes", "No",
    "Yes", "No",
    "Great to see you again", "Who the hell are you?",
    "Store", "Friends", "Leave",
    "Me", "My Mom", "My Teacher", "Nobody",
    "1", "2", "3", "4",
    "Yes", "No",
    "Susie", "Key", "Anything", "Nothing",
    "She's nice", "Terrible", "Eats Chalk", "...",
    "Yes", "No",
    "Sleep", "Do not",
    "Sleep!!!", "Do not!!!",
    "Play a game", "Do not play a game",
    "Play a game", "Do not play a game",
    "Use Key", "Do not",
    "Blaze", "Do Not Blaze",
    "Apologize Profusely", "Intimidate",
    "Listen", "Do Not",
    "Prison B1", "Floor 1F", "??????",
    "Ride", "Do not",
    "Yes", "Don't",
    "Let's Fight", "Let's Not",
    "Me", "Asriel", "Flowers",
    // the warp doors are formatted weird as hell in the code but I think this is the most true to how it's implemented
    // albeit not to how you're supposed to perceive them 
    "Field", "Forest", "Forest", "Bake Sale", "Castle",
    "Give Cake", "Do not",
    "Take Cake", "No",
    "Yes", "No",
    "Yes", "No",
    "Sweet", "Soft", "Sour", "Salty", "Pain", "Cold",
    "A", "AB", "B", "C", "D",
    "Red", "Blue", "Green", "Cyan",
    "Kindness", "Mind", "Ambition", "Bravery", "Voice",
    "Love", "Hope", "Disgust", "Fear",
    "Yes", "No",
    "Yes", "No",
    "Yes", "No",
    // ch2
    "Yes", "No",
    "Lost sleep from being Susie's partner", "Actually my sleep quality increased",
    "Hanging out alone in the closet", "Crime",
    "Hug", "No",
    "Hell yeah!", "No...",
    "Bosom", "Perish",
    "Lie and say you want to hear more", "Stop Conversation",
    "Inspect", "Do not",
    "Dark World", "...",
    "Complain About Police", "Talk About School", "See ya",
    "Yes", "No",
    "Let's go! Let's go!", "We can use the computer at my house",
    "Talk", "Susie", "Don't",
    "Talk More", "Don't talk more",
    "Cause they care", "Your family is weird",
    "Noelle", "Family", "Jockington", "Nothing",
    "Gerson", "Hammer", "Asriel", "Nothing",
    "Current situation", "Susie", "Noelle", "Nothing",
    "Take it", "Do not",
    "You", "Someone Else", "No", 
    "Go with Ralsei", "Go with Susie",
    "Yeah", "Not yet",
    "Wondering", "Don't care",
    "Wondering", "Really don't care",
    "Of course", "No Triple Trucies",
    "We're friends", "We're something else",
    "Buy", "Talk", "Leave",
    "Take", "Don't",
    "Buy", "Don't Buy",
    "Buy", "No",
    "Kris", "Susie", "Noelle", "Ralsei",
    "Go Inside", "Don't go in",
    "Give to Ralsei", "Give to Susie", "Give to Noelle", "Give to Berdly",
    "We have a truce", "She is our enemy",
    "Yes", "No",
    "Noelle", "Ralsei", "You", "...",
    "I am going to touch the cheese", "I do not touch the cheese",
    "Yes", "No",
    "Check Recruits", "Prize", "Nothing",
    "Fuse Items", "Fix Us", "Chat", "Leave",
    "Take Cookie", "Do Not",
    "Grazing", "Hitbox", "Hole", "Nothing",
    "Challenge", "Nothing",
    "Join", "Do not join",
    "I feel the same", "It's strange",
    "Thinking of Noelle", "Thinking of Susie", "Thinking of Berdly", "Thinking of you",
    "It's nice that Ralsei is Ralsei", "...",
    "Do not pose", "Hug Ralsei", "Peace sign", "Rude gesture",
    "Dark World", "Evil Queen's Castle",
    "Point and hearts come out", "Eat Moss",
    "Do something nuts", "Do something crazy",
    "Say something romantic", "Say something cool",
    "Lie", "Lie",
    "Yes", "No",
    "Yes", "No",
    "Yes", "No",
    "Check Recruits", "Recommendation", "Exit",
    "Yes", "No",
    "Left", "Right", "Top", "Bottom",
    "Left", "Right", "Top", "Bottom",
    "Left", "Right", "Top", "Bottom",
    "Buy", "Don't Buy",
    "Buy 400 bagels", "Buy 1 bagel", "Don't buy",
    "Look in the back", "Look inside",
    "Read", "Don't",
    "Occupation", "See brother", "Buy things", "Nothing",
    "Play", "Do not",
    "Give chocolate", "Hoard chocolate",
    "Yes", "No",
    "Yes", "Nooooo",
    "It's horrible", "It's natural",
    "Seems a little far fetched", "Yeah let's do it",
    "Of course", "Of course not",
    "Yes", "No",
    "Yes", "No",
    "Yes", "No",
    "Proceed", "I'm protecting her from you!",
    "Gaming is my life", "Gaming is not my life",
    "They like you", "Unknown", "Yes",
    "Yes", "No",
    "Yes", "No",
    "I will ride with you", "Susie would", "Susie wouldn't",
    "Noelle will ride with me", "Sorry",
    "Yes", "No",
    "Mansion", "Cyber Field", "Trash Zone", "Cancel",
    "Sorry, I'll do the puzzle", "Proceed",
    "Let's solve it together!", "Proceed",
    "Get it", "We're fine",
    "Get it", "We're fine",
    "To see your father", "To see you",
    "In your dream", "...",
    "Because it wasn't a dream", "...",
    "Take", "Do Not",
    "Yes", "No",
    "Sorry, I'll do the puzzle", "Proceed",
    "Sorry, I'll do the puzzle", "Proceed",
    "Sorry, I'll do the puzzle", "Proceed",
    "Sorry, I'll do the puzzle", "Proceed",
    "Yes", "No",
    "Recruits", "Item storage", "Controls", "Do not read",
    "Yes", "No",
    "Yes", "No",
    "Yes", "No",
    "Yes", "No",
    "Yes", "No",
    //ch3
    "Of course. Games are fun", "No",
    "Yes", "No",
    "Buy", "Don't Buy",
    "Yes", "No",
    "Buy something", "Talk more", "Nothing else",
    "Enter", "Do not",
    "Play", "Don't play",
    "Yes", "No",
    "Strike a cool pose", "Strike a glamorous pose",
    "Buy", "Don't Buy",
    "$50 -> 10 PTs", "$250 -> 60 PTs", "$1000 -> 250 PTs", "Don't exchange",
    "Sarcasm", "Everything I say is serious",
    "Yes", "No",
    "Here to cheat", "Got Lost looking for Lancer",
    "Fight it out", "Get Caught",
    "Got Lost looking for the exit",
    "Back here to do good deeds",
    "Obviously", "No thanks",
    "Explain please", "Let's go!",
    "Still not ready", "Ready",
    "Sleep", "Do not",
    "Buy", "Don't Buy",
    "Give 1500 POINTs", "No thanks",
    "Instructions please", "Let's go",
    "Enter Code", "Do Not",
    "Super fun", "Eh",
    "Yes", "Not yet...",
    "Need instructions", "Don't need instructions to rock",
    "Cheater", "Not Really",
    "Where I came from", "Here",
    "No", "Yes",
    "Yes", "Not Yet",
    "Fight him", "Press his buttons", "Don't do anything",
    "Sign", "Don't",
    "Buy TV Dinner for $250", "Don't",
    "Love", "Hate",
    "Yes", "......Yes",
    "Playing games", "Nothing",
    "My rank, my rewards?", "What's in each door?", "Don't",
    "Yes", "No",
    "Check scores", "Tips and Tricks", "Nothing",
    "Check scores", "Tips and Tricks", "Nothing",
    "Check scores", "Tips and Tricks", "Nothing",
    "Play COOKING SHOW", "Quit",
    "Play ROCK VIDEO", "Quit",
    "Normal Mode", "Difficult Mode", "Don't play",
    "Pay 500 points", "Don't",
    "Play MYSTERY GAME", "Play MONSTER MOVIE", "Quit",
    "Enter", "Do Not",
    "Enter", "Do Not",
    "Help or Don't Help", "Pick him up", "No response",
    "See what Susie's doing", "Let's just chill dude",
    "Eyes closed", "Eyes open",
    "Your face", "No",
    "Seen it before", "Cute", "Unique",
    "Talking", "Trying to close eyes and think about Susie",
    "He's fun", "He sucks",
    "Let's go", "Wait",
    "Let me talk", "Nah",
    "Lanino", "Nothing",
    "You're strong and independant", "Your forecast is love",
    "Weather report", "Nothing",
    "You're strong and independant", "Your forecast is love",
    "Ask Susie how she's doing", "Ask Ralsei how he's doing", "Don't",
    "I'm not a dream", "Your friendships are real", "Sucks to be you",
    "It's ok to take it easy", "Stay on task",
    "I'm not going with her", "I'm saying it's from me", "Of course",
    "Noelle", "Ralsei or bust", "Berdly", "Not going",
    "Yes", "No",
    "Hear more", "Enough",
    "Hear more", "No more",
    "Hear more", "Please no more",
    "Yes", "No",
    "50 PTs -> $50", "200 PTs -> $250", "1000 PTs -> $1500", "Don't exchange",
    "Buy 1 for $300", "Buy 3 for $800", "Nope",
    "TV World Entrance", "Goulden Sam", "Green Room", "Cancel",
    "Read it", "Don't read it",
    "She Look Very Nice", "Sorry this is happening",
    "Let's pay attention", "Look in pocket for fun",
    "Put a sticker in a good place", "Put a sticker in a bad place",
    "Noelle, run! She'll drink your blood", "Get closer! She'll drink your blood",
    "Yes", "No",
    "Yes please", "No, you have it",
    "Draw something", "Do nothing",
    "Accurate", "Looks bad chief",
    "Make Susie drawing talk", "Do nothing",
    "Write something in the corner", "Do nothing",
    "Yes", "No",
    "Explain the clues", "Not yet",
    "...", "Me",
    "It was a joke", "Because it wasn't a dream",
    "Sorry, just a prank", "I heard",
    "Sorry, just a prank", "It's not a coincidence",
    "Red", "Blue",
    "Green", "Black",
    "It snowed", "It happened",
    "Noelle will get stronger", "Noelle becomes stronger",
    "Equip", "Equip",
    "Proceed", "Proceed",
    "Proceed", "Proceed",
    "Proceed", "Proceed",
    "Equip", "Equip",
    "Equip", "Equip",
    "Please be yourself", "Of course not",
    "Say what's on your mind", "Say nothing",
    "Yes", "No",
    "Go with Berdly", "Sing the wrong number song",
    "Enter the shelter", "Bangin' sermon my man", "Asgore",
    "Shelter", "Susie will not be tamed",
    "Shelter", "Laugh", "Don't laugh",
    "Offer juice", "Drink juice in front of her",
    "Shelter", "No!",
    "Architectural history research", "Put hay inside, new house for Susie",
    "She gave you chocolates though", "It's because of me",
    "Add 25% red juice", "Add 25% yellow juice", "Empty drink",
    "Asgore", "Key", "Noelle",
    "Nice singing", "Key", "Locked door",
    "Take it", "Do not",
    "Favorites History", "Cat Petterz 4", "Do Not Click",
    "Yes", "No",
    "Old family photo", "Asriel photo", "Don't show either",
    "Discuss plans", "Leave very fast",
    "Tomorrow", "Susie", "Leave",
    "Heat him up", "Leave him",
    "Talk about Catty", "Eavesdrop on blue bunny", "Leave",
    "Yes", "No",
    "Susie", "Parents", "Leave",
    "Read", "Do not",
    "Hear more", "Do not",
    "Inquire about what's going on", "Leave",
    "Change the RPM", "Press the stop button",
    "Offer to give your TV", "Nothing",
    "Investigate", "Do not",
    "Talk about the knight", "Leave", "Jester",
    "Susie ate the clothes", "I ate the clothes",
    "Yes", "No",
    "Show", "Don't show",
    "Store", "What are you doing", "Knight", "Nothing",
    "Sure", "Seems unnecessary",
    "Close eyes for just a moment", "Don't",
    "No", "Think of The Knight", "Think of Noelle",
    "Yes", "No",
    "Go Susie! Go Susie!", "Sorry, not enough time",
    "Listen to it", "Keep walking around",
    "It's okay not to smile", "Good. Keep smiling",
    "That's right", "Prayer",
    "Pray for Susie", "Pray for Noelle", "Pray for Asriel", "Do nothing",
    "Open", "Don't",
    "Mess with them", "Don't",
    "Listen (it might be long)", "Not now",
    "I'll play again someday", "If you play too", "I'll never play again",
    "Advice where to go", "Cute...", "Nothing",
    "No", "Yes", "Two lumps please",
    "Ralsei eat the cake", "That's my cake",
    "Yes", "No",
    "Drink it", "Don't drink",
    "Not now", "Actually I will have tea",
    "Sleep through service", "Watch service",
    "Yes", "No",
    "Yeah", "Nah",
    "Undyne", "Shelter", "Nothing",
    "But we aren't logical", "But Mom could be in there",
    "Dig through", "Don't dig through",
    "Check the panel", "Don't",
    "Outfit", "Are you okay", "Nothing",
    "Yes", "No",
    "Sure", "Not from you",
    "Play (Normal)", "Play (Hard)",
    "Suggest Tenna", "Don't suggest anything",
    "Photo pose!", "Nothing",
    "Jump down", "Wait a sec",
    "Turn the doornob", "Do not",
    "Buy", "Do not", "Why do you need money",
    "Ask", "Don't ask",
    "Don't sleep", "Sleep an incredibly long time",
    "Enter code", "Do not",
];
